{{- range $name, $attrs := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
    {{- if .labels }}
      {{- include "common.tplvalues.render" (dict "value" .labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .annotations $.Values.commonAnnotations }}
  annotations:
    {{- if $.Values.commonAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .annotations }}
      {{- include "common.tplvalues.render" (dict "value" .annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $attrs.clusterSecretStoreName }}
  refreshInterval: {{ $attrs.refreshInterval | quote | default "0" }}
  {{- with $attrs.target }}
  target:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  {{- with $attrs.data }}
  data:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  {{- with $attrs.dataFrom }}
  dataFrom:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
{{- end }}

