{{- range $rbac := .Values.rbac }}
{{- if $rbac.serviceAccount }}
{{- if $rbac.serviceAccount.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $rbac.serviceAccount.secret.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $rbac.serviceAccount.name }}
  labels:
    app.kubernetes.io/managed-by: rbac
type: kubernetes.io/service-account-token
{{- end }}
{{- end }}
{{- end }}
