{{- range $rbac := .Values.rbac }}
{{- if $rbac.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $rbac.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: rbac
{{- end }}
{{- end }}
